#!/bin/bash
echo "Railway Database Schema Setup"
echo "============================="
echo ""
echo "1. Go to your Railway project dashboard"
echo "2. Click on PostgreSQL service"
echo "3. Go to 'Variables' tab"
echo "4. Copy the DATABASE_URL value"
echo "5. Run the following commands:"
echo ""
echo "export DATABASE_URL=\"paste-your-railway-database-url-here\""
echo "npm run db:push"
echo ""
echo "This will create all tables in your Railway PostgreSQL database."